version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: stockflow-postgres
    environment:
      POSTGRES_DB: stockflow
      POSTGRES_USER: stockflow
      POSTGRES_PASSWORD: stockflow
    ports:
      - "5432:5432"
    volumes:
      - stockflow-data:/var/lib/postgresql/data

volumes:
  stockflow-data:
